# fly.toml app configuration file for DealBrief Admin
app = 'dealbrief-admin'
primary_region = 'sea'

[build]

[processes]
  app = "npm start"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'  # Keep machines running
  auto_start_machines = true
  min_machines_running = 1    # Always keep 1 machine running
  processes = ['app']

[env]
  NODE_ENV = "production"
  PORT = "3000"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ['app']